server:
   port: 80

spring:
   datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:vftdb
      username: sa
      password:
   h2:
      console:
         enabled: true

mybatis:
   type-aliases-package: com.shytaani.vfts.entity